Repository lulebe/jscrusades, pull requests merged in 2022-04, with the labels that each got.

#8 Add README.md
  README.md
Labels: documentation

#10 Initial ai integration
  static/js/controller.js
  static/js/gamedata/ai.js
  static/js/gamedata/field.js
  static/js/gamedata/game.js
  static/js/gamedata/gameInfo.js
  static/js/gamedata/gameLoader.js
  static/js/gamedata/legacy/ai.js
  static/js/gamedata/legacy/compat.js
  static/js/gamedata/legacy/compat.ts
  static/js/gamedata/mapInfo.js
  static/js/gamedata/unit.js
  static/js/online.js
  static/js/ui.js
Labels: feature

#11 Bug fixes
  static/js/audio.js
  static/js/controller.js
  static/js/gamedata/game.js
  static/js/gamedata/unit.js
Labels: bug

#12 Ai no timers
  static/js/gamedata/ai.js
  static/js/gamedata/legacy/ai.js
  static/js/gamedata/legacy/compat.js
Labels: feature
